import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Anda Tech Solutions</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to my articles!
        </h1>

        <div className={styles.grid}>
          <Link href="/react-graphql-node-e2e-testing" className={styles.card}>
            <h2>Integration and E2E testing with React, GraphQL, Node and Mongo, and mocking the time &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="mailto:anda.nenu@gmail.com">
          <Image src="/profile.jpeg" alt="Anda" width={50} height={50} style={{ borderRadius: '50%' }} />
          Contact me
        </a>
      </footer>
    </div>
  )
}
